# Generated by Django 5.0.1 on 2025-07-22 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Domaine",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom du schéma PostgreSQL pour django-tenants",
                        max_length=63,
                        unique=True,
                        verbose_name="Nom du schéma PostgreSQL",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email principal"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "siret",
                    models.CharField(blank=True, max_length=14, verbose_name="SIRET"),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de TVA"
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Forme juridique"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_trial",
                    models.BooleanField(
                        default=True, verbose_name="En période d'essai"
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de la période d'essai"
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("trial", "Essai gratuit"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        max_length=50,
                        verbose_name="Plan d'abonnement",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5, verbose_name="Nombre maximum d'utilisateurs"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        default=1, verbose_name="Stockage maximum (GB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Créé par (user_id)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="tenants_name_bc4541_idx"),
                    models.Index(fields=["domain"], name="tenants_domain_726e44_idx"),
                    models.Index(
                        fields=["is_active"], name="tenants_is_acti_ec1713_idx"
                    ),
                    models.Index(
                        fields=["subscription_plan"], name="tenants_subscri_3ab647_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantBankInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="BIC/SWIFT"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de la banque"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_info",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informations bancaires",
                "verbose_name_plural": "Informations bancaires",
                "db_table": "tenant_bank_info",
            },
        ),
        migrations.CreateModel(
            name="TenantDocumentAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_text",
                    models.TextField(blank=True, verbose_name="Texte d'en-tête"),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Texte de pied de page"),
                ),
                (
                    "show_logo",
                    models.BooleanField(default=True, verbose_name="Afficher le logo"),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("left", "Gauche"),
                            ("center", "Centre"),
                            ("right", "Droite"),
                        ],
                        default="left",
                        max_length=10,
                        verbose_name="Position du logo",
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Arial", max_length=50, verbose_name="Police"
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(default=11, verbose_name="Taille de police"),
                ),
                (
                    "line_spacing",
                    models.FloatField(default=1.5, verbose_name="Interligne"),
                ),
                (
                    "margin_top",
                    models.IntegerField(default=25, verbose_name="Marge supérieure"),
                ),
                (
                    "margin_right",
                    models.IntegerField(default=20, verbose_name="Marge droite"),
                ),
                (
                    "margin_bottom",
                    models.IntegerField(default=25, verbose_name="Marge inférieure"),
                ),
                (
                    "margin_left",
                    models.IntegerField(default=20, verbose_name="Marge gauche"),
                ),
                (
                    "show_payment_details",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les détails de paiement"
                    ),
                ),
                (
                    "show_legal_mentions",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les mentions légales"
                    ),
                ),
                (
                    "legal_mentions",
                    models.TextField(blank=True, verbose_name="Mentions légales"),
                ),
                (
                    "table_header_color",
                    models.CharField(
                        default="#f8f9fa",
                        max_length=10,
                        verbose_name="Couleur en-tête tableau",
                    ),
                ),
                (
                    "table_alternate_color",
                    models.CharField(
                        default="#f2f2f2",
                        max_length=10,
                        verbose_name="Couleur alternée tableau",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_appearance",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apparence des documents",
                "verbose_name_plural": "Apparence des documents",
                "db_table": "tenant_document_appearance",
            },
        ),
        migrations.CreateModel(
            name="TenantPaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                ("days", models.IntegerField(default=0, verbose_name="Jours")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Par défaut"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_terms",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition de paiement",
                "verbose_name_plural": "Conditions de paiement",
                "db_table": "tenant_payment_terms",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Paris",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="Langue"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD/MM/YYYY",
                        max_length=20,
                        verbose_name="Format de date",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="URL du logo"
                    ),
                ),
                (
                    "logo_data",
                    models.TextField(
                        blank=True,
                        help_text="Logo encodé en base64",
                        verbose_name="Données du logo (base64)",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        max_length=10,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        max_length=10,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#28a745",
                        max_length=10,
                        verbose_name="Couleur d'accent",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications par email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notifications par SMS"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications push"
                    ),
                ),
                (
                    "password_expiry_days",
                    models.IntegerField(
                        default=90, verbose_name="Expiration mot de passe (jours)"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.IntegerField(
                        default=5, verbose_name="Tentatives de connexion max"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        default=480, verbose_name="Timeout session (minutes)"
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False,
                        verbose_name="Authentification à 2 facteurs obligatoire",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres Tenant",
                "verbose_name_plural": "Paramètres Tenants",
                "db_table": "tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="TenantDocumentNumbering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Facture"),
                            ("quote", "Devis"),
                            ("order", "Commande"),
                            ("delivery", "Bon de livraison"),
                            ("credit_note", "Avoir"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=10, verbose_name="Préfixe"),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=10, verbose_name="Suffixe"),
                ),
                (
                    "next_number",
                    models.IntegerField(default=1, verbose_name="Prochain numéro"),
                ),
                (
                    "padding",
                    models.IntegerField(
                        default=4,
                        help_text="Nombre de chiffres pour le numéro (ex: 4 pour 0001)",
                        verbose_name="Nombre de chiffres",
                    ),
                ),
                (
                    "include_year",
                    models.BooleanField(default=True, verbose_name="Inclure l'année"),
                ),
                (
                    "include_month",
                    models.BooleanField(default=False, verbose_name="Inclure le mois"),
                ),
                (
                    "reset_yearly",
                    models.BooleanField(
                        default=True, verbose_name="Réinitialiser chaque année"
                    ),
                ),
                (
                    "reset_monthly",
                    models.BooleanField(
                        default=False, verbose_name="Réinitialiser chaque mois"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_numbering",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numérotation de document",
                "verbose_name_plural": "Numérotations de documents",
                "db_table": "tenant_document_numbering",
                "unique_together": {("tenant", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email de l'invité"),
                ),
                ("invited_by", models.UUIDField(verbose_name="Invité par (user_id)")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("admin", "Administrateur"),
                            ("manager", "Manager"),
                        ],
                        default="user",
                        max_length=50,
                        verbose_name="Rôle",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Acceptée"),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="Expirée"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acceptée le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Tenant",
                "verbose_name_plural": "Invitations Tenants",
                "db_table": "tenant_invitations",
                "indexes": [
                    models.Index(fields=["token"], name="tenant_invi_token_8b1449_idx"),
                    models.Index(fields=["email"], name="tenant_invi_email_39a62c_idx"),
                    models.Index(
                        fields=["expires_at"], name="tenant_invi_expires_74dd72_idx"
                    ),
                ],
                "unique_together": {("tenant", "email")},
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "active_users_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre d'utilisateurs actifs"
                    ),
                ),
                (
                    "storage_used_gb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Stockage utilisé (GB)",
                    ),
                ),
                (
                    "api_calls_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'appels API"),
                ),
                (
                    "logins_count",
                    models.IntegerField(default=0, verbose_name="Nombre de connexions"),
                ),
                (
                    "documents_created",
                    models.IntegerField(default=0, verbose_name="Documents créés"),
                ),
                (
                    "documents_updated",
                    models.IntegerField(default=0, verbose_name="Documents modifiés"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation Tenant",
                "verbose_name_plural": "Utilisations Tenants",
                "db_table": "tenant_usage",
                "indexes": [
                    models.Index(
                        fields=["tenant", "date"], name="tenant_usag_tenant__9c6f5e_idx"
                    ),
                    models.Index(fields=["date"], name="tenant_usag_date_f761ac_idx"),
                ],
                "unique_together": {("tenant", "date")},
            },
        ),
        migrations.CreateModel(
            name="TenantVatRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Par défaut"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_rates",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de TVA",
                "verbose_name_plural": "Taux de TVA",
                "db_table": "tenant_vat_rates",
                "unique_together": {("tenant", "code")},
            },
        ),
    ]
