# Generated by Django 5.2 on 2025-07-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = []
