# Generated by Django 5.2 on 2025-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_enhance_document_numbering"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="vat_number",
        ),
        migrations.AddField(
            model_name="tenant",
            name="ice",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="ICE (Identifiant Commun de l'Entreprise)",
            ),
        ),
    ]
