# Generated by Django 5.0.1 on 2025-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_add_ice_remove_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="document_template",
            field=models.CharField(
                choices=[
                    ("modern", "Moderne"),
                    ("classic", "Classique"),
                    ("minimal", "Minimal"),
                ],
                default="modern",
                max_length=20,
                verbose_name="Modèle de document",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="primary_color",
            field=models.CharField(
                default="#1B333F",
                help_text="Couleur principale utilisée dans les documents (format HEX)",
                max_length=10,
                verbose_name="Couleur principale",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_bank_details",
            field=models.BooleanField(
                default=True, verbose_name="Afficher les coordonnées bancaires"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_client_address",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'adresse du client"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_notes",
            field=models.BooleanField(default=True, verbose_name="Afficher les notes"),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_payment_terms",
            field=models.BooleanField(
                default=True, verbose_name="Afficher les conditions de paiement"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_project_info",
            field=models.BooleanField(
                default=True, verbose_name="Afficher les informations du projet"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_signature_area",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la zone de signature (devis)"
            ),
        ),
    ]
