# Generated by Django 5.2 on 2025-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenantdocumentappearance_document_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_info",
            field=models.BooleanField(
                default=True, verbose_name="Afficher les informations de l'entreprise"
            ),
        ),
    ]
