# Generated by Django 5.0.1 on 2025-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_add_show_company_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantdocumentappearance",
            name="show_company_info",
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_address",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'adresse de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_email",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'email de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_ice",
            field=models.BooleanField(default=True, verbose_name="Afficher l'ICE"),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_name",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le nom de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_phone",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le téléphone de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_siret",
            field=models.BooleanField(default=True, verbose_name="Afficher le SIRET"),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_website",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le site web de l'entreprise"
            ),
        ),
    ]
