# Generated by Django 5.2 on 2025-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_alter_tenantsettings_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="logo_center_in_header",
            field=models.BooleanField(
                default=False,
                help_text="Centrer le logo quand il est placé dans l'en-tête",
                verbose_name="Centrer le logo dans l'en-tête",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="logo_data",
            field=models.TextField(
                blank=True,
                help_text="Logo encodé en base64",
                verbose_name="Données du logo (base64)",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="logo_position_type",
            field=models.CharField(
                choices=[
                    ("left", "À gauche"),
                    ("top", "En haut"),
                    ("header", "Dans l'en-tête"),
                ],
                default="left",
                help_text="Position principale du logo dans le document",
                max_length=10,
                verbose_name="Type de position du logo",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="logo_size",
            field=models.IntegerField(
                default=100,
                help_text="Taille du logo en pourcentage (50-200%)",
                verbose_name="Taille du logo (%)",
            ),
        ),
    ]
