# Generated by Django 5.2 on 2025-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_add_advanced_logo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="section_contrast",
            field=models.BooleanField(
                default=False,
                help_text="Alterner les couleurs de fond des sections/chapitres",
                verbose_name="Sections contrastées",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="section_contrast_color",
            field=models.CharField(
                default="#f8f9fa",
                help_text="Couleur de fond pour les sections alternées",
                max_length=10,
                verbose_name="Couleur de contraste des sections",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_section_subtotals",
            field=models.BooleanField(
                default=True,
                help_text="Afficher les sous-totaux dans les titres des sections/chapitres",
                verbose_name="Afficher les sous-totaux des sections",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_border_color",
            field=models.CharField(
                default="#dee2e6",
                help_text="Couleur des bordures du tableau",
                max_length=10,
                verbose_name="Couleur des bordures",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_border_horizontal",
            field=models.BooleanField(
                default=True,
                help_text="Afficher les bordures horizontales entre les lignes",
                verbose_name="Bordures horizontales",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_border_style",
            field=models.CharField(
                choices=[("straight", "Droites"), ("rounded", "Arrondies")],
                default="straight",
                help_text="Style des bordures des cellules du tableau",
                max_length=20,
                verbose_name="Style des bordures",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_border_vertical",
            field=models.BooleanField(
                default=True,
                help_text="Afficher les bordures verticales entre les colonnes",
                verbose_name="Bordures verticales",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_border_width",
            field=models.IntegerField(
                default=1,
                help_text="Épaisseur des bordures en pixels",
                verbose_name="Épaisseur des bordures (px)",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_column_spacing",
            field=models.IntegerField(
                default=12,
                help_text="Espacement horizontal entre les colonnes",
                verbose_name="Espacement des colonnes (px)",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="table_row_padding",
            field=models.IntegerField(
                default=8,
                help_text="Espacement vertical à l'intérieur des cellules",
                verbose_name="Espacement des lignes (px)",
            ),
        ),
    ]
