# Generated by Django 5.2 on 2025-07-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_add_advanced_table_styles"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="payment_methods_layout",
            field=models.CharField(
                choices=[
                    ("horizontal", "Horizontal (côte à côte)"),
                    ("vertical", "Vertical (empilés)"),
                    ("grid", "Grille (2 colonnes)"),
                ],
                default="horizontal",
                help_text="Comment disposer les cartes de moyens de paiement",
                max_length=20,
                verbose_name="Disposition des moyens de paiement",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="payment_methods_style",
            field=models.CharField(
                choices=[
                    ("modern", "Moderne (avec ombres)"),
                    ("classic", "Classique (bordures simples)"),
                    ("minimal", "Minimal (sans bordures)"),
                ],
                default="modern",
                help_text="Style visuel des cartes de moyens de paiement",
                max_length=20,
                verbose_name="Style des cartes de paiement",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="payment_methods_title",
            field=models.CharField(
                default="Moyens de paiement",
                help_text="Titre affiché au-dessus des moyens de paiement",
                max_length=100,
                verbose_name="Titre de la section moyens de paiement",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_payment_methods",
            field=models.BooleanField(
                default=True,
                help_text="Afficher la section des moyens de paiement dans les documents",
                verbose_name="Afficher les moyens de paiement",
            ),
        ),
        migrations.CreateModel(
            name="TenantPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Virement bancaire"),
                            ("check", "Chèque"),
                            ("cash", "Espèces"),
                            ("card", "Carte bancaire"),
                            ("paypal", "PayPal"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type de moyen de paiement",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nom affiché du moyen de paiement",
                        max_length=100,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description ou instructions pour ce moyen de paiement",
                        verbose_name="Description",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détails spécifiques (IBAN, RIB, instructions, etc.)",
                        verbose_name="Détails spécifiques",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher ce moyen de paiement dans les documents",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage dans la liste (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône à afficher (ex: bank, credit-card)",
                        max_length=50,
                        verbose_name="Nom de l'icône",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#f8f9fa",
                        help_text="Couleur de fond de la carte du moyen de paiement",
                        max_length=10,
                        verbose_name="Couleur de fond",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#212529",
                        help_text="Couleur du texte sur la carte",
                        max_length=10,
                        verbose_name="Couleur du texte",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#dee2e6",
                        help_text="Couleur de la bordure de la carte",
                        max_length=10,
                        verbose_name="Couleur de la bordure",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyen de paiement",
                "verbose_name_plural": "Moyens de paiement",
                "db_table": "tenant_payment_methods",
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="tenant_paym_tenant__1c610f_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="tenant_paym_display_521f3a_idx"
                    ),
                ],
                "unique_together": {("tenant", "method_type")},
            },
        ),
    ]
