# Generated by Django 5.2 on 2025-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_add_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="slogan",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Slogan/description de l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocumentappearance",
            name="show_company_slogan",
            field=models.BooleanField(
                default=True,
                verbose_name="Afficher le slogan/description de l'entreprise",
            ),
        ),
    ]
