# Generated by Django 5.2 on 2025-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_add_slogan_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantdocumentappearance",
            name="logo_data",
            field=models.TextField(
                blank=True,
                help_text="Logo encodé en base64",
                null=True,
                verbose_name="Données du logo (base64)",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="logo_data",
            field=models.TextField(
                blank=True,
                help_text="Logo encodé en base64",
                null=True,
                verbose_name="Données du logo (base64)",
            ),
        ),
    ]
