# Generated by Django 5.0.1 on 2025-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_add_slogan_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
