# Generated by Django 5.2 on 2025-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_alter_tenantdocumentappearance_logo_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de finalisation de la création des schémas",
                null=True,
                verbose_name="Schémas créés le",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="schema_error",
            field=models.TextField(
                blank=True,
                help_text="Détails de l'erreur si la création a échoué",
                verbose_name="Erreur de création",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="schema_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Détails de progression de la création des schémas",
                verbose_name="Progression de la création",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="schema_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de création"),
                    ("creating", "Création en cours"),
                    ("ready", "Prêt"),
                    ("error", "Erreur de création"),
                ],
                default="pending",
                help_text="Statut de la création des schémas de données pour les services",
                max_length=20,
                verbose_name="Statut des schémas",
            ),
        ),
    ]
