# Generated by Django 5.0.1 on 2025-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenant_schema_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slogan",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Slogan/description de l'entreprise",
            ),
        ),
    ]
