# Generated by Django 5.0.1 on 2025-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_alter_tenant_slogan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_progress",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="schema_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
